# Generated by Django 6.1 on 2026-08-28 14:19

from django.db import migrations

def create_groups_and_assign_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    ticket_content_type = ContentType.objects.get(
        app_label='tickets',
        model='ticket'
    )

    permission_view = Permission.objects.get(content_type=ticket_content_type, codename='view_ticket')
    permission_add = Permission.objects.get(content_type=ticket_content_type, codename='add_ticket')
    permission_change = Permission.objects.get(content_type=ticket_content_type, codename='change_ticket')

    group_user, _ = Group.objects.get_or_create(name='User')
    group_support, _ = Group.objects.get_or_create(name='Support')
    group_manager, _ = Group.objects.get_or_create(name='Manager')

    group_user.permissions.add(permission_view, permission_add)

    group_support.permissions.add(permission_view, permission_add, permission_change)

    group_manager.permissions.add(permission_view, permission_add, permission_change)

def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['User', 'Support', 'Manager']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('users', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_assign_permissions, remove_groups)
    ]
